# Generated by Django 4.1.7 on 2023-04-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('horariosFuncionamento', models.CharField(max_length=100)),
                ('avaliacao', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('imagemFundoURL', models.CharField(max_length=300)),
                ('iconeURL', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('P', 'Pizzaria'), ('H', 'Hamburgueria'), ('J', 'Japa'), ('C', 'Comidas Tradicionais'), ('D', 'Doceria'), ('I', 'Italiano'), ('O', 'Outras')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('fotoURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RestauranteFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurantefavorito', to='reservapp.restaurante')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurantefavorito', to='reservapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('numeroPessoas', models.IntegerField()),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservapp.restaurante')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('tipoItem', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemcardapio', to='reservapp.restaurante')),
            ],
        ),
    ]
