name: Django Rest Framework Unit Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test